// Generated by CoffeeScript 1.3.3
(function() {
  var phantom;

  phantom = require('phantom');

  describe('Array', function() {
    return it('should return -1 when the value is not present', function(done) {
      return phantom.create(function(ph) {
        return ph.createPage(function(page) {
          return page.open("http://www.google.com", function(status) {
            console.log("opened google? ", status);
            page.evaluate((function() {
              return document.title;
            }), function(result) {});
            console.log('Page title is ' + result);
            ph.exit();
            return done();
          });
        });
      });
    });
  });

}).call(this);
