// Generated by CoffeeScript 1.3.3
(function() {
  var Browser, should, _;

  Browser = require("zombie");

  _ = require("underscore");

  should = require("should");

  describe("the main page", function() {
    var browser;
    browser = new Browser();
    before(function(done) {
      return browser.visit("http://localhost:3000/", {
        element: "#login-box"
      }, function() {
        return done();
      });
    });
    return it("should show login", function() {
      return browser.text("#login-title").should.equal("Welcome to PoL!");
    });
  });

  describe("the main page", function() {
    var browser;
    browser = new Browser();
    before(function(done) {
      return browser.visit("http://localhost:3000/auth/facebook", function() {
        return done();
      });
    });
    return it("should show lobby", function() {
      return console.log(browser.html());
    });
  });

  describe("the login box", function() {
    var browser;
    browser = new Browser();
    before(function(done) {
      return browser.visit("http://localhost:3000/", {
        element: "#login-box"
      }, function() {
        return done();
      });
    });
    return it("should contain facebook link", function() {
      var urls;
      urls = _.map(browser.queryAll("#login-box a"), function(link) {
        return link.attributes.href.value;
      });
      return urls.should.include("/auth/facebook");
    });
  });

}).call(this);
