// Generated by CoffeeScript 1.3.3
(function() {

  describe("DOM Tests", function() {
    var el, myEl;
    el = document.createElement("div");
    el.id = "myDiv";
    el.innerHTML = "Hi there!";
    el.style.background = "#ccc";
    document.body.appendChild(el);
    myEl = document.getElementById("myDiv");
    it("is in the DOM", function() {
      return expect(myEl).to.not.equal(null);
    });
    it("is a child of the body", function() {
      return expect(myEl.parentElement).to.equal(document.body);
    });
    it("has the right text", function() {
      return expect(myEl.innerHTML).to.equal("Hi there!");
    });
    return it("has the right background", function() {
      return expect(myEl.style.background).to.equal("rgb(204, 204, 204)");
    });
  });

}).call(this);
